powsybl/powsybl-network-store

.github/workflows/maven.yml
README.md

No
Github actions  configuration

CI status badge

---

.github/workflows/maven.yml
network-store-client/src/main/java/com/powsybl/network/store/client/BufferedRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CacheNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkFactoryImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkObjectIndex.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreService.java
network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/tools/NetworkStoreDeleteTool.java
network-store-client/src/main/java/com/powsybl/network/store/client/tools/NetworkStoreListTool.java
network-store-client/src/main/java/com/powsybl/network/store/client/tools/NetworkStoreScriptTool.java
network-store-client/src/test/java/com/powsybl/network/store/client/RestNetworkStoreClientTest.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/NetworkAttributes.java
network-store-model/src/test/java/com/powsybl/network/store/model/ResourceTest.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql
network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@gmail.com>
#12 

Use a network UUID in primary key

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CacheNetworkStoreClient.java

No
Bug fix
In #12, a regression has been added in network resources caching.
Regressions is fixed.
(if …

Fix network resources caching

---

network-store-client/src/main/java/com/powsybl/network/store/client/NetworkObjectIndex.java

No
Feature
NetworkObjectIndex is complex and use multiple maps for object indexing.
NetworkObjectIndex has been refactored to only use one map per equipment type.
**Does this PR introduce a breaking change or deprecate an …

Simplify objects indexing

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CacheNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkObjectIndex.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/StaticVarCompensatorAdderImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/StaticVarCompensatorImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/VoltageLevelImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/SvcTestCaseFactory.java
network-store-model/src/main/java/com/powsybl/network/store/model/ResourceDeserializer.java
network-store-model/src/main/java/com/powsybl/network/store/model/StaticVarCompensatorAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql

- [X ] The commit message follows our guidelines
#2
(if any of the questions/checkboxes don't apply, please delete …

Implementation of SVC storage

---

.github/workflows/maven.yml
pom.xml

No
Feature => docker image build and upload to Github packages, only on master branch

Docker build

---

.github/workflows/maven.yml

No
Feature
Docker image is published to Github packages
Docker image is published to DockerHub

Use DockerHub instead of Github packages

---

.github/workflows/maven.yml

No
feature
When network store client is updated in master, downstream micro-services that depends on it are not updated.
An update event is broadcasted to all repos.
**Does this PR introduce a breaking change or deprecate an …

Broadcast update event

---

pom.xml

No
feature
Single diagram version dependency is 1.0.0
Single diagram version dependency is 1.1.0
(if any …

Update single line diagram to 1.1.0

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CacheNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreService.java

No
Bug fix
REST cache is flushed, sometimes before extensions have been added. 
REST cache is not automatically flushed when getting new data
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check …

Fix cache inconsistency

---

network-store-client/src/main/java/com/powsybl/network/store/client/NetworkImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/NodeBreakerViewImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/VoltageLevelAdderImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/VoltageLevelImpl.java
network-store-model/src/main/java/com/powsybl/network/store/model/VoltageLevelAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql

- [ X] The commit message follows our guidelines
This PR introduces some missing implementations for data storage.
It also adds the storage of the nodeCount attribute of the NodeBreakerViewImpl in Cassandra DB. …

Modifications for cgmes import

---

network-store-server/src/main/java/com/powsybl/network/store/server/CassandraConfig.java

no
Bug fix
We get a null pointer exception if iidm keyspace has not been created
An exception with a clear message is thrown in case of missing iidm keyspace …

Throws an exception in case of missing IIDM keyspace

---

network-store-client/src/main/java/com/powsybl/network/store/client/ThreeWindingsTransformerImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStorageTestCaseFactory.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/LegAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql

Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>
#4 implements CurrentLimits for ThreeWindingsTransformer

add currentLimits on threewindings

---

network-store-server/src/main/java/com/powsybl/network/store/server/CassandraConfig.java

No
Cleanup
Use IIDM keyspace variable already created.

CassandraConfig cleanup

---

network-store-client/src/main/java/com/powsybl/network/store/client/AbstractBranchImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/AbstractInjectionImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/BusbarSectionImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/TerminalBusBreakerViewImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/TerminalImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/ThreeWindingsTransformerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/VoltageLevelImpl.java
network-store-model/src/main/java/com/powsybl/network/store/model/BranchAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/InjectionAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql

No
Bug fix
Bus/breaker topology implementation has bugs and does not allow single line diagram generation.
Bus/breaker topology implementation has been fixed. …

Fix bus/breaker topology

---

network-store-client/src/main/java/com/powsybl/network/store/client/AbstractIdentifiableImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java

Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>
#50

fix getName

---

network-store-client/src/main/java/com/powsybl/network/store/client/CacheNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingRestNetworkStoreClient.java

Fix second level cache

---

network-store-client/src/main/java/com/powsybl/network/store/client/GeneratorImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/VariantManagerImpl.java

No
feature
In order to got further in loadflow integration, new mocks need to be added.
VariantManager and Network.BusView mocks have been added.
**Does this PR introduce a breaking change or deprecate an API?** *If yes, …

Additional mocks

---

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql

- [] Tests for the changes have been added (for bug fixes / features)
No
Bug fix
Switches in bus/breaker topo are not created/loaded correctly.
Switches in bus/breaker topo are now correctly created/loaded.
**Does this PR …

Fix bus/breaker switch creation/loading

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CacheNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/LazyLoadingRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkObjectIndex.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreService.java
network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java

No
refactoring
This is just a very simple refactoring

Just simple refactoring

---

network-store-client/src/main/java/com/powsybl/network/store/client/AbstractRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/BufferedRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CachedRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/Resources.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/SwitchAdderBusBreakerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/SwitchAdderNodeBreakerImpl.java
network-store-client/src/test/java/com/powsybl/network/store/client/CachedRestNetworkStoreClientTest.java
network-store-client/src/test/java/com/powsybl/network/store/client/RestNetworkStoreClientTest.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/pom.xml
network-store-model/src/main/java/com/powsybl/network/store/model/AbstractAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/AttributesSpyer.java
network-store-model/src/main/java/com/powsybl/network/store/model/IdentifiableAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/Resource.java
network-store-model/src/main/java/com/powsybl/network/store/model/ResourceDeserializer.java
network-store-model/src/main/java/com/powsybl/network/store/model/SwitchAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/UpdateResource.java
network-store-model/src/test/java/com/powsybl/network/store/model/ResourceTest.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java
pom.xml

Add cassandra requests for updating a switch or a list of switches in the NetworkStoreRepository
Add services for updating a switch or a list of switches in NetworkStoreController
Add methods in interface NetworkStoreClient for updating a switch or a list of switches
Implementing these methods in the different implementations of this interface
Implement the notification mechanism to inform the networkStoreClient interface every time a switch is modified 
Signed-off-by: Franck LECUYER <franck.lecuyer@rte-france.com> …

Create network modification server

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CachedRestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingRestNetworkStoreClient.java
network-store-client/src/test/java/com/powsybl/network/store/client/CachedRestNetworkStoreClientTest.java
network-store-client/src/test/java/com/powsybl/network/store/client/PreloadingRestNetworkStoreClientTest.java

update resource performance problem

---

.github/workflows/maven.yml
network-store-client/src/main/java/com/powsybl/network/store/client/AbstractIdentifiableImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/CalculatedBus.java
network-store-client/src/main/java/com/powsybl/network/store/client/DanglingLineImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/InternalConnectionAdderNodeBreakerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/PhaseTapChangerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/RatioTapChangerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/ThreeWindingsTransformerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/XnodeAdderImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/XnodeAdderImplProvider.java
network-store-client/src/main/java/com/powsybl/network/store/client/XnodeImpl.java
network-store-server/pom.xml
pom.xml

Signed-off-by: Jon Harper <jon.harper87@gmail.com>
NO
Feature
powsybl 3.1
powsybl 3.2
NO

Upgrade to powsybl-core 3.2.0

---

network-store-client/src/main/java/com/powsybl/network/store/client/CalculatedBus.java
network-store-client/src/main/java/com/powsybl/network/store/client/StaticVarCompensatorImpl.java

No
Bug fix
Upgrade to PowSyBl 3.3.0, new IIDM 1.2 API and OLF 0.3 has introduced regression with "TODO" exception for not implemented part of the IIDM API.  
Mock have been added.
**Does this PR introduce a breaking change or …

Add new IIDM mocks to fix PowSyBl 3.3.0 upgrade regressions

---

network-store-client/src/main/java/com/powsybl/network/store/client/CalculatedBus.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java

No
Bug fix
Lot's of methods in `CalculatedBus` to access equipments have not been implemented.
These methods are implemented. …

Implement missing equipment accessors in CalculatedBus

---

network-store-server/src/test/java/com/powsybl/network/store/test/EmbeddedCassandraFactoryConfig.java
pom.xml

No
Bug fix
timeouts in CI
hopefully no more timeouts in CI
NO

Cassandra tests: up the timeout to 15 minutes

---

network-store-client/src/main/java/com/powsybl/network/store/client/TwoWindingsTransformerAdderImpl.java

Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>

Override setRatedS

---

network-store-client/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlAdderImplNetworkStoreProvider.java
network-store-client/src/main/java/com/powsybl/network/store/client/AbstractBranchImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/AbstractIdentifiableImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/DanglingLineImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkObjectIndex.java
network-store-client/src/main/java/com/powsybl/network/store/client/PhaseTapChangerAdderImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/PhaseTapChangerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/RatioTapChangerAdderImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/RatioTapChangerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/ShuntCompensatorImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/SubstationImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/ThreeWindingsTransformerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/TwoWindingsTransformerAdderImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/TwoWindingsTransformerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/VoltageLevelImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStorageTestCaseFactory.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java

No
Bug fix
Numbers of methods necessary for import since powsybl core 3.3.0 and also for xiidm export have not been implemented ot mocked.
These methods have been either implemented or mocked.
**Does this PR introduce a …

Add mocks to be able to convert to XIIDM

---

network-store-client/src/main/java/com/powsybl/network/store/client/AbstractBranchImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/AbstractIdentifiableImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/AbstractInjectionImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/AbstractTopology.java
network-store-client/src/main/java/com/powsybl/network/store/client/BusbarSectionImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/CalculatedBus.java
network-store-client/src/main/java/com/powsybl/network/store/client/DanglingLineImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/GeneratorImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/HvdcLineImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkCache.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkObjectIndex.java
network-store-client/src/main/java/com/powsybl/network/store/client/NodeBreakerTopology.java
network-store-client/src/main/java/com/powsybl/network/store/client/NodeBreakerViewImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/ShuntCompensatorImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/SubstationImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/ThreeWindingsTransformerImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/TwoWindingsTransformerImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/ActivePowerControlAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/BranchAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/CalculatedBusAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/GeneratorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/LineAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/TwoWindingsTransformerAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/CassandraConfig.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql

Various fixes (including regressions)

---

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java

No
Bug fix
Shunt update Cassandra query is not correctly built.
Shunt update Cassandra query is correct. …

Fix shunt update query

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractBranchImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractInjectionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionPositionAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionPositionAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionPositionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConnectablePositionAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConnectablePositionAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConnectablePositionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java

NO
Feature
ConnectablePosition support is a hack (copy values from resources to an extension object). It doesn't support updates.
Using the new powsybl 3.2 api, an networkstore implementation of ConnectablePosition allows proxying calls to the resource.
**Does this PR introduce a breaking change or …

Connectableposition

---

network-store-iidm-impl/src/main/java/com/powsybl/iidm/network/extensions/ThreeWindingsTransformerPhaseAngleClockAdderImplNetworkStoreProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/iidm/network/extensions/TwoWindingsTransformerPhaseAngleClockAdderImplNetworkStoreProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/iidm/network/extensions/VoltagePerReactivePowerControlAdderImplNetworkStoreProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorAdderImpl.java

Bug fix
Exceptions occurs when copying a network in memory into the network store with NetworkXml copy method, because there are some classes or methods, necessary since powsybl core 3.4, not yet implemented or mocked.
These classes and methods have been implemented or mocked.
**Does this PR …

Add mock code necessary for NetworkXml.copy method

---

README.md

Signed-off-by: yichen88 <tang.yichenyves@gmail.com>

Fix cassandra download link

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/Edge.java
network-store-model/src/main/java/com/powsybl/network/store/model/InternalConnectionAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/SwitchAttributes.java

**What kind of change does this PR introduce?** Implementation of isConnected() method in TeminalImpl
**What is the current behavior?** No implementation
**What is the new behavior (if this is a feature change)?** We use the buses value to determine the terminal connection

Implement isConnected() methode for terminals

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusBreakerTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerTopology.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java

No
Bug fix
Calculated bus view from a bus breaker voltage level is not correct:
- lines and transformers connected multiple time at the same voltage level is not taken into account
- calculated bus definition is not the same as in mem IIDM impl 
**What is the new behavior (if this is …

Fix bus view calculation from bus breaker model issue

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TieLineAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TieLineImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreValidationTest.java

No
Bug fix
TieLine impl is incorrect, both half are not filled.
TieLine impl is now similar to in mem impl.
**Other …

Fix tieline implementation

---

pom.xml

No
Bug fix
powsybl-single-line-diagram master is 1.6.0-SNAPSHOT

Use Single Line Diagram 1.6.0-SNAPSHOT

---

network-store-client/src/test/java/com/powsybl/network/store/client/PreloadingNetworkStoreClientTest.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/DanglingLineAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/DanglingLineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorLinearModelImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorModelOwner.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorNonLinearModelImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TieLineImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStorageTestCaseFactory.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreValidationTest.java
network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorLinearModelAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorModelAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorNonLinearModelAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorNonLinearSectionAttributes.java
network-store-model/src/test/java/com/powsybl/network/store/model/ResourceTest.java
network-store-server/src/main/java/com/powsybl/network/store/server/CassandraConfig.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql
network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java
pom.xml

powsybl 3.5 update for shunt compensators

---

network-store-client/src/main/java/com/powsybl/network/store/client/CollectionCache.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConfiguredBusImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VariantManagerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VoltageLevelImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/Resource.java

This PR add new methods implementations to ensure a load flow will run correctly on a MergingView based on NetworkStore network implementation
(if any of the questions/checkboxes …

Fix mergingview loadflow

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/LegAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql

No
feature
ratedS attribute of 3 windings transformer legs is not implemented
ratedS attribute of 3 windings transformer legs is implemented …

Implement winding leg ratedS

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StaticVarCompensatorImpl.java

pb_with_static_var_compensators_set_point_methods

---

network-store-server/pom.xml

Signed-off-by: Jon Harper <jon.harper87@gmail.com>
NO
Bug Fix
curl localhost:8080/actuator/health gives the error whitelabel page
curl localhost:8080/actuator/health gives the health
NO
**Other …

Fix actuator

---

network-store-iidm-impl/src/main/java/com/powsybl/iidm/network/extensions/LoadDetailAdderImplNetworkStore.java
network-store-iidm-impl/src/main/java/com/powsybl/iidm/network/extensions/LoadDetailImplNetworkStore.java
network-store-iidm-impl/src/main/java/com/powsybl/iidm/network/extensions/SlackTerminalAdderImplNetworkStore.java
network-store-iidm-impl/src/main/java/com/powsybl/iidm/network/extensions/SlackTerminalAdderImplNetworkStoreProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/iidm/network/extensions/SlackTerminalImplNetworkStore.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CalculatedBus.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConfiguredBusImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LoadImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VoltageLevelImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/LoadAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/LoadDetailAttributes.java
pom.xml

No
This PR prepares the upgrade of powsybl-core version to 3.6.0

Prepare powsybl-core 3.6.0 release

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java

Implementation of getI() method for a terminal

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java

No
Bug fix
Batteries are not implemented yet.
Part of the battery api is mocked to allow hades run
(if …

Add battery mock

---

.github/workflows/maven.yml
pom.xml

Use single line diagram release

---

.github/workflows/maven.yml

Remove single line diagram build notification as we now use release

---

network-store-iidm-impl/src/main/java/com/powsybl/cgmes/conversion/extensions/CgmesSvMetadataAdderImplNetworkStoreProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/cgmes/conversion/extensions/CimCharacteristicsAdderImplNetworkStoreProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/SlackTerminalImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
pom.xml

No
feature
PowSyBl core 3.6.0 is used
PowSyBl core 3.7.1 is used and downstream project are updated consistently.
**Other …

Migrate to PowSyBl core 3.7.1

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CachedNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java
network-store-client/src/test/java/com/powsybl/network/store/client/PreloadingNetworkStoreClientTest.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/HvdcLineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/OfflineNetworkStoreClient.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java

No.
Add implementation for removing hvdc lines.
There's no implementation. A TODO exception is raised.
Methods for removing hvdc lines are implemented.
No.

Implement remove hvdc line

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CachedNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java
network-store-client/src/test/java/com/powsybl/network/store/client/PreloadingNetworkStoreClientTest.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractInjectionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LccConverterStationImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LoadImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/OfflineNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StaticVarCompensatorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VscConverterStationImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java

**Does this PR already have an issue describing the problem ?**
No.
Add implementations for removing components  :
- BusBarSection
- Generator
- LccConverterStation
- Line
- Load
- ShuntCompensator
- StaticVarCompensator
- ThreeWindingsTransformer
- TieLine
- TwoWindingsTransformer
- VscConverterStation
There's no implementation for those components. A TODO exception is raised.
**What is the new behavior (if this is a feature …

Implement remove method for components

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreService.java
network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingNetworkStoreClient.java
network-store-client/src/test/java/com/powsybl/network/store/client/CachedNetworkStoreClientTest.java
network-store-iidm-impl/pom.xml
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CachedNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CollectionCache.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ForwardingNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkCollectionIndex.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkFactoryImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/CollectionCacheTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/NetworkFactoryServiceImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/OfflineModeTest.java

No
Bug fix
Network store offline mode (without server backing) does not work.
Network store offline mode works
**Other …

Fix offline mode

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusBreakerViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConfiguredBusImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/TopologyTraverserTest.java

- [ X] The commit message follows our guidelines
No
Implement the topology traverser from a terminal necessary to launch Hades2
Topology traverser from a terminal is not implmented and Hades2 is launched from a powsybl core network (via a copy)
Topology traverser from a terminal is implemented …

Implement topology traverser from terminal

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java

No.
Implementation of the getConnectable methods.
Implementation isn't done.
Methods are implemented.

Implement getConnectable

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java
network-store-client/src/test/java/com/powsybl/network/store/client/PreloadingNetworkStoreClientTest.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractForwardingNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CachedNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CollectionCache.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/OfflineNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ResourceUpdaterImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/CollectionCacheTest.java

No
Refactoring
There is useless (count) and redundant (update and remove) methods in `NetworkStoreClient`. 
We have removed every getXXXCount methods, remove(id), and update(id) …

Network store client simplification

---

network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingNetworkStoreClient.java

Revert PR #177

---

network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingNetworkStoreClient.java

Fix network preloading performance issue

---

network-store-server/src/main/resources/iidm.cql

Signed-off-by: Jon Harper <jon.harper87@gmail.com>
NO
Bug Fix
most of the iidm.cql script is idempotent without errors, but a small part of it is not.
iidm.cql idempotent without errors
NO

Add missing ifnotexists to iidm.cql

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RatioTapChangerAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RatioTapChangerImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreValidationTest.java

Adapt check ratio tap changer to powsybl core 4.0.1

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/HvdcLineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/HvdcAngleDroopActivePowerControlAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/HvdcAngleDroopActivePowerControlAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/HvdcAngleDroopActivePowerControlImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/HvdcOperatorActivePowerRangeAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/HvdcOperatorActivePowerRangeAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/HvdcOperatorActivePowerRangeImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/HvdcAngleDroopActivePowerControlAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/HvdcLineAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/HvdcOperatorActivePowerRangeAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/CassandraConfig.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql

Implementation of the new extensions for hvdc lines, introduced in powsybl core 4.0.0
Unable to import some cases in the network store, due to the lack of these hvdc extensions implementation
The cases can now be imported in the network store
**Does this PR introduce a breaking change or deprecate …

Implementation of new extensions for hvdc lines

---

network-store-iidm-impl/pom.xml
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BaseBus.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/DanglingLineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TieLineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/CgmesModelExtensionAdderImplNetworkStoreProvider.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/BoundaryTest.java

No
Bug fix
New Boundary interface has been added in 4.0.1 but is not yet implemented in network store.  
Boundary is now implemented …

Boundary implementation

---

network-store-server/src/main/java/com/powsybl/network/store/server/CassandraConfig.java
network-store-server/src/main/java/com/powsybl/network/store/server/CassandraConstants.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/application.yml
network-store-server/src/main/resources/iidm.cql
network-store-server/src/test/java/com/powsybl/network/store/test/EmbeddedCassandraFactoryConfig.java
network-store-server/src/test/resources/create_keyspace.cql
network-store-server/src/test/resources/truncate.cql

Feature
Cassandra keyspace name is hard coded : 'iidm'
Cassandra keyspace name is now configurable (in the application.yaml file)
(if any of the questions/checkboxes don't apply, …

Make cassandra keyspace configurable

---

network-store-iidm-impl/src/main/java/com/powsybl/cgmes/extensions/CgmesDanglingLineBoundaryNodeAdderNetworkStoreImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/cgmes/extensions/CgmesLineBoundaryNodeAdderNetworkStoreImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/BoundaryTest.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
pom.xml

Migrate to PowSyBl Core 4.2.0

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImpl.java
network-store-model/src/main/java/com/powsybl/network/store/model/BatteryAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/BusAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/BusbarSectionAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ConfiguredBusAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/DanglingLineAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/GeneratorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/HvdcLineAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/LccConverterStationAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/LineAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/LoadAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/NetworkAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/StaticVarCompensatorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/SubstationAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/SwitchAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ThreeWindingsTransformerAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/TwoWindingsTransformerAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/VoltageLevelAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/VscConverterStationAttributes.java
network-store-model/src/test/java/com/powsybl/network/store/model/ResourceTest.java
network-store-model/src/test/java/com/powsybl/network/store/model/TopLevelDocumentTest.java

Refactor alias init

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/DanglingLineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TieLineAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TieLineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/RemoteReactivePowerAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/RemoteReactivePowerControlAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/RemoteReactivePowerControlAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/RemoteReactivePowerControlImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreValidationTest.java
network-store-model/src/main/java/com/powsybl/network/store/model/GeneratorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/MergedXnodeAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/RemoteReactivePowerControlAttributes.java
network-store-model/src/test/java/com/powsybl/network/store/model/AttributesTest.java
network-store-server/src/main/java/com/powsybl/network/store/server/CassandraConfig.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/resources/iidm.cql
pom.xml

NO
Feature
powsyb 4.3.2
powsybl 4.3.1
cassandra migration

powsybl 4.3.1 migration

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CollectionBuffer.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java
network-store-client/src/test/java/com/powsybl/network/store/client/CollectionBufferTest.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CachedNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CollectionCache.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkCollectionIndex.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/OfflineNetworkStoreClient.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/CollectionCacheTest.java

Index resources by variant number

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java

Network object index refactoring

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CachedNetworkStoreClient.java

Simplify cache and buffer implementation

---

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java

Improve network delete performance

---

.github/workflows/maven.yml
README.md

NO
feature
default git branch is master
default git branch is main
NO

switch git branch master to main

---

network-store-server/src/main/java/com/powsybl/network/store/server/CassandraConfig.java

Append powsybl cassandra keyspace prefix property to the keyspace name if exists.

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ReactiveCapabilityCurveAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TemporaryLimitApparentLimitAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TemporaryLimitCurrentLimitAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerAdderImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/CalculatedBusAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/CgmesSshMetadataAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/HvdcLineAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/LccConverterStationAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/NetworkAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/StaticVarCompensatorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/VscConverterStationAttributes.java
network-store-model/src/test/java/com/powsybl/network/store/model/TopLevelDocumentTest.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreApplication.java

Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>

Fix members initialization to match powsybl-core one.

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/CollectionBuffer.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CachedNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CollectionCache.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/Resource.java

NO
bugfix
write buffer deletes not flushed in the new variant
write buffer updates flushed as creates in the new variant
write buffer deletes flushed in the new variant
write buffer updates flushed as updates in the new variant
**Does this PR introduce a breaking change or deprecate an API?** *If …

fix write buffer bug with variants (update flushed as create, missing delete flushes)

---

network-store-server/src/main/java/com/powsybl/network/store/server/Session.java

NO
add commit() and rollback() to networkstore batches
no commit ? don't know what the postgres jdbc driver does.
NO

add commit() and rollback(), missing since setting setAutocommit(false)

---

pom.xml

Signed-off-by: Seddik Yengui <seddik.yengui@rte-france.com>

Spring boot 2.6.6 migration

---

pom.xml

Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>

Remove proxy profile which was only useful for cassandra

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/GeneratorEntsoeCategoryAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/GeneratorEntsoeCategoryAdderProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/GeneratorEntsoeCategoryImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/GeneratorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/GeneratorEntsoeCategoryAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/Mappings.java
network-store-server/src/main/resources/schema.sql

Signed-off-by: jacques borsenberger <jacques.borsenberger@rte-france.com>

add extension genertorEnstsoeCategory

---

pom.xml

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@gmail.com>
#258 

Fix Java 18 build

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusBreakerTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerTopology.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/NodeBreakerTerminalTest.java

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@gmail.com>

Revert calculated bus naming

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImpl.java
network-store-model/src/main/java/com/powsybl/network/store/model/BatteryAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/BusAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/BusbarSectionAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ConfiguredBusAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/DanglingLineAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/GeneratorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/HvdcLineAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/LccConverterStationAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/LineAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/LoadAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/NetworkAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/StaticVarCompensatorAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/SubstationAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/SwitchAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ThreeWindingsTransformerAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/TwoWindingsTransformerAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/VoltageLevelAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/VscConverterStationAttributes.java
network-store-model/src/test/java/com/powsybl/network/store/model/ResourceTest.java
network-store-model/src/test/java/com/powsybl/network/store/model/TopLevelDocumentTest.java

Alias memory optimization

---

network-store-server/src/main/java/com/powsybl/network/store/server/exceptions/RestResponseEntityExceptionHandler.java

Log exception as an error in RestResponseEntityExceptionHandler

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BatteryImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/DanglingLineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LccConverterStationImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LoadImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StaticVarCompensatorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VscConverterStationImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/NpeGetConnectableTerminalWhenRemovingLine.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/NpeGetConnectableTerminalWhenRemovingLineTest.java

NPE on getConnectableTerminals after removing a line

---

network-store-server/src/main/resources/config/application.yaml

NO
feature/bugfix
default hikari minimum idle of 1
default hikari minimum idle of 10
NO
Spring boot default is 10

Add hikari minimum-idle 10

---

.github/workflows/maven.yml

Fix Sonar in CI

---

network-store-server/src/main/java/com/powsybl/network/store/server/ColumnMapping.java
network-store-server/src/main/java/com/powsybl/network/store/server/Mappings.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/java/com/powsybl/network/store/server/QueryCatalog.java
network-store-server/src/main/java/com/powsybl/network/store/server/TableMapping.java

No
Refactoring
Code is simplified by adding more infos to table mapping

Add more infos to table mapping

---

network-store-server/src/main/java/com/powsybl/network/store/server/Mappings.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/java/com/powsybl/network/store/server/TableMapping.java

No
Bug fix
Resource builder are reused because of a regression in PR #277 
Resource builder are recreated for each resource creation …

Fix resources creation

---

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/main/java/com/powsybl/network/store/server/QueryCatalog.java
network-store-server/src/main/resources/config/application.yaml

Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>

Replace TemporaryLimits multi deletion queries by a unique query by variantNum with IN statement

---

network-store-model/src/main/java/com/powsybl/network/store/model/ThreeWindingsTransformerAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/Mappings.java

Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>

Factorize ThreeWindingsTransformerAttributes leg's attributes mappings

---

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractBranchAdder.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusBreakerViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CachedNetworkStoreClient.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/PointAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ReactiveCapabilityCurveImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorAdderImpl.java
network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreToolsIT.java
network-store-model/src/main/java/com/powsybl/network/store/model/DanglingLineAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
pom.xml

Use PowSyBl parent 9

---

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java

Signed-off-by: BOUTIER Charly <charly.boutier@rte-france.com>

Fixes a bug that converts double values to int in the reactive capability curves

---

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java

Bug fix
Study duplication consumes JSON, which is not correct and send 415 errors
Study duplication does not consume JSON anymore

Study duplication fix

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StaticVarCompensatorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/StandbyAutomatonAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/StandbyAutomatonAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/StandbyAutomatonImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/StandbyAutomatonTest.java
network-store-model/src/main/java/com/powsybl/network/store/model/StandbyAutomatonAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/StaticVarCompensatorAttributes.java
network-store-server/src/main/java/com/powsybl/network/store/server/Mappings.java
network-store-server/src/main/resources/db/changelog/changesets/changelog_2022-12-13T21:23:00Z.xml
network-store-server/src/main/resources/db/changelog/db.changelog-master.yaml

Standby automaton extension

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerViewImpl.java

Fix internal connexion removal

---

network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

No
Feature
1.0.0-SNAPSHOT
1.1.0-SNAPSHOT

Prepare release v1.0.0

---

network-store-client-distribution/pom.xml
pom.xml

Fix Sonar code coverage

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/PointAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ReactiveCapabilityCurveAdderImpl.java

Add control qmax greater than qmin

---

network-store-iidm-impl/pom.xml
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractBranchImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractInjectionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalBusBreakerViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalBusViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalNodeBreakerViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/NodeBreakerTerminalTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/TopologyTraverserTest.java

Fix updateResource misuse

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/PhaseTapChangerAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RatioTapChangerAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TapChangerParent.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerImpl.java

Fix tapChanger update

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/PhaseTapChangerAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/PhaseTapChangerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RatioTapChangerAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RatioTapChangerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TapChangerParent.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerTest.java

Remove tap changer

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Release 1.3.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump 1.4.0-SNAPHOT

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BatteryImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CalculatedBus.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StaticVarCompensatorAdderImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/CreateNetworksUtil.java

NO
remove deprecated stuff that will be removed from powsybl 6
using deprecated
not using stuff removed in https://github.com/powsybl/powsybl-core/pull/2611
NO

Powsybl6 deprecations

---

network-store-client/pom.xml
network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreService.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestClientImpl.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java
network-store-client/src/main/java/com/powsybl/network/store/client/RestTemplateResponseErrorHandler.java
network-store-client/src/test/java/com/powsybl/network/store/client/RestNetworkStoreClientTest.java
network-store-iidm-impl/pom.xml
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractBranchAdder.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractInjectionAdder.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerTopology.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/SubstationUtil.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VoltageLevelUtil.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/HvdcOperatorActivePowerRangeImpl.java
network-store-model/pom.xml
network-store-model/src/main/java/com/powsybl/network/store/model/ReactiveLimitsAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorModelAttributes.java
pom.xml

springboot 3.2

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

release 1.5.0

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CalculatedBus.java

Empty implementation for getProperty() on CalculatedBus

---

pom.xml

powsybl dependencies 2023.3.2 + ws-commons 1.7.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

release 1.6.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

bump v1.7.0-SNAPSHOT

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/ActivePowerControlImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/ActivePowerControlExtensionTest.java

Fix active power control modification, notify when update droop or participate.

---

README.md
network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

No
Release
1.7.0-SNAPSHOT
1.8.0-SNAPSHOT

Prepare release v1.7.0

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VoltageLevelImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/SlackTerminalRemoveIssueTest.java

Slack terminal extension removal

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/CgmesTapChangersImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/CgmesTapChangersTest.java

No
Bug fix
`CgmesTapChangers` extension is not correctly implemented and not sync with core implementation.
getTapChanger returns null when not found instead of throwing an exception.

Fix CgmesTapChangers extension implementation

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/CgmesControlAreaImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/CgmesControlAreasTest.java

No
Bug fix
Cgmes control areas extension is not fully implemented.

Fix Cgmes control areas extension

---

pom.xml

Fix typo in Sonar config

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableToInjectionAttributesAdapter.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BranchToInjectionAttributesAdapter.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionToInjectionAdapter.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerToInjectionAttributesAdapter.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/BusBarSectionToInjectionAdapterTest.java

Fix duplication for https://github.com/powsybl/powsybl-network-store/pull/383

Refacto duplication

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.10.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.11.0-SNAPSHOT

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractBranchImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractInjectionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java

Fix new extensions

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/BranchObservabilityAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/BranchObservabilityAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/BranchObservabilityImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/BranchObservabilityLoader.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/InjectionObservabilityAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/InjectionObservabilityAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/InjectionObservabilityImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/InjectionObservabilityLoader.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/ObservabilityQualityImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/extensions/BranchObservabilityTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/extensions/InjectionObservabilityTest.java
network-store-model/src/main/java/com/powsybl/network/store/model/BranchObservabilityAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/InjectionObservabilityAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ObservabilityQualityAttributes.java

Feature
BranchObservability and InjectionObservability extensions are not yet implemented.
BranchObservability and InjectionObservability extensions are now implemented.

Implement BranchObservability and InjectionObservability extensions

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/ThreeWindingsTransformerToBeEstimatedAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/ThreeWindingsTransformerToBeEstimatedAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/ThreeWindingsTransformerToBeEstimatedImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/ThreeWindingsTransformerToBeEstimatedLoader.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/TwoWindingsTransformerToBeEstimatedAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/TwoWindingsTransformerToBeEstimatedAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/TwoWindingsTransformerToBeEstimatedImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/TwoWindingsTransformerToBeEstimatedLoader.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/extensions/ThreeWindingsTransformerToBeEstimatedTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/extensions/TwoWindingsTransformerToBeEstimatedTest.java
network-store-model/src/main/java/com/powsybl/network/store/model/ThreeWindingsTransformerToBeEstimatedAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/TwoWindingsTransformerToBeEstimatedAttributes.java

Feature
TwoWindingsTransformerToBeEstimated and ThreeWindongsTransformerToBeEstimated extensions are not yet implemented.
TwoWindingsTransformerToBeEstimated and ThreeWindongsTransformerToBeEstimated are now implemented.

Implement TwoWindingsTransformerToBeEstimated and ThreeWindingsTransformerToBeEstimated extensions.

---

pom.xml

Remove the unused powsybl-ws-commons dependencies from network-store. It fixes the dependency relation betwen network-store and powsybl-ws-commons.

Remove ws commons dependency

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.14.0

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/ControlUnitAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/ControlUnitImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/ControlZoneAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/ControlZoneImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/PilotPointAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/PilotPointImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/SecondaryVoltageControlAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/SecondaryVoltageControlAdderImplProvider.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/SecondaryVoltageControlImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/SecondaryVoltageControlLoader.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/extensions/SecondaryVoltageControlTest.java
network-store-model/src/main/java/com/powsybl/network/store/model/ControlUnitAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/ControlZoneAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/PilotPointAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/SecondaryVoltageControlAttributes.java

Feature
SecondaryVoltageControl extension is not implemented
SecondaryVoltageControl is now implemented

implement SecondaryVoltageControl extension

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.15.0-SNAPSHOT

---

network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/AreaTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/ComponentCalculationBugWhenMergingTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/ConnectableTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/ConnectionNotificationTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/MoveConnectableNotifTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/NetworkReportNodeTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/OperationalLimitsGroupsTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/OverloadManagementSystemTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/SubnetworksCreationTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/SubnetworksExplorationTest.java

add comment in tck about overridden tests

add info about override in tck

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConfiguredBusImpl.java

Bug fix
Potential NPE in getCalculatedBusAttribute method in ConfiguredBusImpl class.
Check added to avoid the NPE.

Fix null pointer exception in ConfiguredBusImpl

---

network-store-iidm-impl/pom.xml
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractInjectionImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BatteryImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/DanglingLineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LccConverterStationImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LineImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LoadImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RegulatingPoint.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StaticVarCompensatorAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StaticVarCompensatorImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VscConverterStationImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/StaticVarCompensatorTest.java
network-store-model/src/main/java/com/powsybl/network/store/model/AbstractIdentifiableAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/RegulationPointAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/StaticVarCompensatorAttributes.java

no
it manages better the terminal regulation for svc and it synchronised with powsybl-core
it is linked to https://github.com/powsybl/powsybl-core/pull/2470
there will be a database modification
liked to https://github.com/powsybl/powsybl-network-store-server/pull/52

add regulation point for svc

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CalculatedBus.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConfiguredBusImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerViewImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/BusTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/NetworkTest.java
network-store-model/src/main/java/com/powsybl/network/store/model/ConfiguredBusAttributes.java
network-store-model/src/main/java/com/powsybl/network/store/model/VoltageLevelAttributes.java

Implement FictitiousP0 and FictitiousQ0 in Bus interface

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

release v1.16.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.17.0 snapshot

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RegulatingPoint.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StaticVarCompensatorAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VscConverterStationAdderImpl.java
network-store-model/src/main/java/com/powsybl/network/store/model/RegulationPointAttributes.java
network-store-model/src/test/java/com/powsybl/network/store/model/ResourceTest.java
network-store-model/src/test/java/com/powsybl/network/store/model/TopLevelDocumentTest.java

Fix regulation point

---

.github/workflows/maven.yml

Update CI
Build docker images for nothing
No docker images build

chore: remove docker steps in CI

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Release v1.17.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.18.0-SNAPSHOT

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Release v1.17.1

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConnectablePositionImpl.java

FIX NPE Direction

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.18.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.19.0-SNAPSHOT

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.19.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.20.0-SNAPSHOT

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

bump to v1.20.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

bump to v1.21.0-SNAPSHOT

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to release 1.21.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

Bump to 1.22.0-SNAPSHOT

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RatioTapChangerAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerTest.java

**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**

fix setting regulating terminal for ratioTapChanger

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/SubstationImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalBusBreakerViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalBusViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalNodeBreakerViewImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VoltageLevelImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/BatteryTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/GeneratorTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/LineTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/SubstationTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/VoltageLevelTest.java

No
This PR allows access to the id of an identifiable when it is deleted
Needed to generate the exception message when accessing a removed identifiable
Some TCK tests fails
TCK tests based on the id when a identifiable is removed succeeded
No change

TCK : normalize exception msg

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorAdderImpl.java
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VscConverterStationAdderImpl.java

No
Check is now implemented in powsybl: https://github.com/powsybl/powsybl-core/blob/7432a7e4d5c037fde860175423ad2cf51fca10bf/iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java#L157-L159

Clean outdated fixme

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

release v2.15.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

bump to v1.26.0-SNAPSHOT

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

release v1.26.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

bump to v1.27.0-SNAPSHOT

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

release v 1.27.0

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

bump to v1.28.0-SNAPSHOT

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VariantManagerImpl.java
network-store-model/src/main/java/com/powsybl/network/store/model/utils/VariantUtils.java

No
Fix typo in method + avoid O(n2) complexity even if this should be really insignificant

Code improvement find variantNum

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-model/pom.xml
pom.xml

release v1.28.0

---

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/OperationalLimitsGroupImpl.java

fix import with properties on limits

---

network-store-client-distribution/pom.xml
network-store-client/pom.xml
network-store-iidm-impl/pom.xml
network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractBranchImpl.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/OperationalLimitsTest.java
network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/OperationalLimitsGroupsTest.java
network-store-model/pom.xml
pom.xml

Prepare release v1.30.1
