powsybl/powsybl-network-store

pom.xml
No
Bug fix
Network store depends on core 3.1.0 and also to single line diagram 1.1.0 but single line diagram depends on core 3.0.0. 
We update single line diagram to 1.2.0 which depends to core 3.1.0
**Does this PR introduce …
=> Migrate to single line diagram v1.2.0

network-store-client/src/main/java/com/powsybl/network/store/client/VoltageLevelImpl.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
This PR introduces various bug fixes discovered when trying to import and visualize a CGMES network:
Corrections of retrieval of lines, two and three windings transformers by voltage level, which used to return the same line (or transformer) twice in the returned list when the line (or transformer) had two of its extremities on the same voltage level. This caused the creation of an erroneous graph when visualizing the network in the …
=> Corrections of cgmes import bugs

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
No
Bug fix
Lines are not correctly managed in bus/breaker topo. In network store repository: bus1, bus2, connectableBus1, connectableBus2 are not saved/queried.
Lines are correctly managed in bus/breaker topo.
**Does this PR …
=> Fix line creation in bus/breaker topo

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedRestNetworkStoreClient.java
No
Bug fix
When getting 3 windings transformers from `BufferedRestNetworkStoreClient` already created resources are flushed.
flush have been removed (like for the other equipments)
**Does this PR introduce a breaking change …
=> Remove 3wt flush

network-store-client/src/main/java/com/powsybl/network/store/client/NodeBreakerViewImpl.java
This fix doesn't fully solve the issue, since that instead of retrieving all switches each time we need to get a single switch (which was the cause of the issue), it only ensures that only the needed switch is retrieved (and not all).
#57 
**What is the new behavior (if this is a feature …
=> Fix the multiple switches retrieval requests

.gitignore, network-store-demo/pom.xml, network-store-demo/src/main/java/com/powsybl/network/store/demo/ClientSingleLineDiagramViewer.java, network-store-demo/src/main/resources/logback.xml, pom.xml
No
feature
A customized version of single line diagram JavaFX demo connected to network store server. 
=> Add single line diagram JavaFX demo connected to network store

network-store-client/src/main/java/com/powsybl/network/store/client/SwitchAdderBusBreakerImpl.java
No
Bug fix
In case of bus/breaker topology, switch kind is not set.
In case of bus/breaker topology, switch kind is set.
**Other …
=> Fix switch kind in case of bus/breaker topo

network-store-client/src/main/java/com/powsybl/network/store/client/AbstractHvdcConverterStationImpl.java, network-store-client/src/main/java/com/powsybl/network/store/client/HvdcLineImpl.java, network-store-client/src/main/java/com/powsybl/network/store/client/LccConverterStationImpl.java, network-store-client/src/main/java/com/powsybl/network/store/client/VscConverterStationImpl.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
No
Bug fix
HvdcConverterStation.getHvdcLine is not implemented.
HvdcConverterStation.getHvdcLine is implemented.
**Other …
=> Implement HVDC converter station to HVDC line link

.github/workflows/maven.yml, README.md, network-store-server/src/test/java/com/powsybl/network/store/server/EmbeddedCassandraFactoryConfig.java
NO
Bug Fix
CI fails and documentation is out of date because casssandra-4-alpha3 is not longer downloadable
using cassandra-4-alpha4
no
=> upgrade to cassandra-4.0-alpha4, alpha3 is no longer available

network-store-client/src/main/java/com/powsybl/network/store/client/NetworkObjectIndex.java
No
Bug fix
When we get a single object from network (like network.getGenerator('A')), not the same instance is returned.
Same instance of the network object is returned to allow identity comparison.
**Does this PR introduce a …
=> Fix network object index

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VariantManagerImpl.java
Replaced by empty implementations
This PR introduces empty implementations of some methods related to variant management, instead of throwing UnsupportedOperationException exceptions
Currently, those unimplemented methods throw UnsupportedOperationException
**What is the new behavior (if this is …
=> Removed TODO exceptions thrown by variant creation/removal methodes

network-store-iidm-impl/src/main/java/com/powsybl/iidm/network/extensions/EntsoeAreaAdderImplNetworkStoreProvider.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/SubstationImpl.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-model/src/main/java/com/powsybl/network/store/model/EntsoeAreaAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/SubstationAttributes.java, network-store-server/src/main/java/com/powsybl/network/store/server/CassandraConfig.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/resources/iidm.cql, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java
This PR fixes a bug when importing a UCTE network.
Currently, when trying to import a UCTE network file, an error is raised due to the lack of implementation of the EntsoeAreaAdder provider for the network store. The extension for the substation dedicated to the EntsoeArea is also not …
=> Implementation of the ExtensionAdderProvider for EntsoeArea

network-store-client/src/main/java/com/powsybl/network/store/client/CollectionCache.java
No
Bug fix
Caching is broken, when loading resources from a container, even if collection has been fully loaded it might is some case query the resource from the server.
Caching has been fixed
**Does this PR introduce a …
=> Fix caching regression when loading container resources

network-store-iidm-impl/src/main/java/com/powsybl/iidm/network/extensions/LoadDetailAdderImplNetworkStoreProvider.java
No
Bug fix
As LoadDetail new extension is not supported we cannot anymore import some CGMES.
A fake LoadDetail extension provider is added to avoid the exception. The full LoadDetail support will be added in another PR. …
=> Add load detail provider to avoid exception

network-store-server/pom.xml, pom.xml
NO
Bug Fix
Using cassandra-driver-core 3.6 and extras 3.7
Using cassandra-driver-core 3.7 and extras 3.7
NO
=> use cassandra-extras 3.7 because spring set cassandra-core 3.7, not 3.6

network-store-client/src/main/java/com/powsybl/network/store/client/RestClient.java
NO
Bug Fix
compilation crash with jdk 11.0.7 and before
compilation works
NO
See
https://stackoverflow.com/questions/54775253/jdk-11-0-2-compilation-fails-with-javac-npe-on-anonymo …
=> Workaroudn compilation crash with jdk11 < 11.0.8

network-store-client/src/main/java/com/powsybl/network/store/client/BufferedNetworkStoreClient.java, network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingNetworkStoreClient.java, network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java, network-store-client/src/test/java/com/powsybl/network/store/client/PreloadingNetworkStoreClientTest.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusBreakerViewImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CachedNetworkStoreClient.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkStoreClient.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerViewImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/OfflineNetworkStoreClient.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/SubstationImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/SubstationUtil.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VoltageLevelImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VoltageLevelUtil.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStorageTestCaseFactory.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java
No
Feature
Substations and voltage levels removal methods are not implemented
Substations and voltage levels removal methods are now implemented and substations and voltage levels can thus be correctly removed from network
**Does this PR …
=> Implementation of substations and voltage levels removal

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BatteryAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConfiguredBusAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/DanglingLineAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/HvdcLineAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LccConverterStationAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LineAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/LoadAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StaticVarCompensatorAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/SubstationAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/SwitchAdderBusBreakerImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/SwitchAdderNodeBreakerImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TieLineAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VoltageLevelAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VscConverterStationAdderImpl.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-model/src/main/java/com/powsybl/network/store/model/ConfiguredBusAttributes.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/resources/iidm.cql
Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>
- [x ] The commit message follows our guidelines
Bug
The  'fictitious'  attribute is not store to Cassandra for some resources
The  'fictitious'  attribute is now store to Cassandra for all resources
**Does this PR introduce a breaking …
=> Add missing fictitious attributes in cassandra

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConfiguredBusAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/DanglingLineAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/SubstationImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VoltageLevelAdderImpl.java, network-store-integration-test/pom.xml, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-model/src/main/java/com/powsybl/network/store/model/BatteryAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/ConfiguredBusAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/DanglingLineAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/GeneratorAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/LineAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/LoadAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/ThreeWindingsTransformerAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/TwoWindingsTransformerAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/VoltageLevelAttributes.java, network-store-model/src/test/java/com/powsybl/network/store/model/ResourceTest.java
This PR must be merged after this one :
https://github.com/powsybl/powsybl-network-store/pull/157
- [x ] The commit message follows our guidelines
Feature
Some attributes are not initiated like powsybl core which generates non-identical xml exports
All attributes are initiated like powsybl core …
=> Initialization of attributes in powsyble core way to have identical xml exports

network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreService.java, network-store-client/src/main/java/com/powsybl/network/store/client/RestClient.java, network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java, network-store-client/src/test/java/com/powsybl/network/store/client/CachedNetworkStoreClientTest.java, network-store-client/src/test/java/com/powsybl/network/store/client/PreloadingNetworkStoreClientTest.java, network-store-client/src/test/java/com/powsybl/network/store/client/RestNetworkStoreClientTest.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/cassandra/NetworkFactoryTestService.java
No
Bug fix
When network store server is accessed concurrently we sometimes end up with such an exception:
```java
essing failed; nested exception is java.util.ConcurrentModificationException] with root cause
java.util.ConcurrentModificationException: null
at …
```
=> Fix concurrency issue

network-store-model/src/main/java/com/powsybl/network/store/model/BatteryAttributes.java
**Does this PR already have an issue describing the problem ?**
Aliases are not taken in the constructor BatteryAttributes(BatteryAttributes other)
Aliases are copied in this constructor.
=> add_aliases_to_battery_attr_constructor

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusBreakerTopology.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/BusBreakerTerminalTest.java
Yes
Load flow calculation fails when a dangling line is disconnected in bus/breaker topology
Bug fix
When a calculation of buses is done for a  bus/breaker  VL, all terminals are used to create the vertices and not only the  connected terminals
When a calculation of buses is done for a  bus/breaker …
=>  Bug fix for bus/breaker vertices in a calculated bus (get only connected terminals)

network-store-client/src/main/java/com/powsybl/network/store/client/PreloadingNetworkStoreClient.java
No
Bug fix
When preloading collection is on, all network resources instances are preloaded not only the asked one.
Only the right network  resource instance is preloaded
**Does this PR introduce a breaking change or deprecate …
=> Fix network preloading performance issue

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CalculatedBus.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java
No
Performance improvement
We have poor performance with pre loading set to none and when we visit equipment connected to a bus.
Performance has been improve by avoiding using getIdentifiable method but typed getConnectable …
=> Improve bus equipment visitor performance

network-store-iidm-impl/pom.xml, network-store-iidm-tck/pom.xml, network-store-integration-test/pom.xml, network-store-model/pom.xml, network-store-server/pom.xml, network-store-tools/pom.xml, pom.xml
NO
Feature
the project has many definitions of versions of artifact that don't match with versions used by the 3rd party projects for compilation and test, so we risk having incompatibilities
Use versions from other projects when we don't care about one specific version
**Does this PR introduce a …
=> maven: use versions from other projects when possible and cleanup a bit

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractBranchImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/BranchStatusAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/BranchStatusAdderImplProvider.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/BranchStatusImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/BranchStatusExtensionTest.java, network-store-model/src/main/java/com/powsybl/network/store/model/BranchAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/LineAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/ThreeWindingsTransformerAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/TwoWindingsTransformerAttributes.java, network-store-model/src/test/java/com/powsybl/network/store/model/ResourceTest.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/resources/iidm.cql
No
This PR introduces the new extension BranchStatus for Lines, Two windings transformers and Three windings transformers. This extension allows to define a specific status for these equipments whether they are in operation, locked-out or tripped and to store it in database.
Currently, there is …
=> Addition of BranchStatus extension and its storage.

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BranchToInjectionAttributesAdapter.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerToInjectionAttributesAdapter.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
No
Bug fix
In node/breaker toplogy, when we connect or disconnect a terminal no notification is sent to listeners
In node/breaker toplogy, when we connect or disconnect a terminal notifications are sent to listeners
=> Fix lockout line in bus/breaker topology

network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreService.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
- [X ] The commit message follows our guidelines
Feature
When we import a network, it is automatically flushed in the database
The flush in database is now optional
=> Make the database flush optional when importing a network

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VariantManagerImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/ManipulationsOnVariantsTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/VariantTest.java
No
Feature
Currently, when a variant is cloned or removed from network store, no notification is sent to the network listener.
Now, when a variant is cloned or removed from network store, a notification of clone/removal of variant is sent to the network listener.
**Does this PR introduce a breaking …
=> Add variant clone/removal notifications

network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorNonLinearModelAttributes.java
No
Bug fix
Currently, serializing and deserializing non linear shunt compensators attributes does not work since some getters are not ignored in json serialization
Non linear shunt compensators attributes are now correctly serialized/deserialized
**Does this PR introduce a breaking change or …
=> Fix non linear shunt compensators Json serialization

network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/resources/schema.sql, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java
NO
BugFix
A voltageLevel without a substation is not stored
stored
NO
=> Fix network-store-server when voltagelevel is not in a substation

network-store-server/src/main/java/com/powsybl/network/store/server/Session.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java
NO
Bugfix
sql errors are swallowed. The whole batch is rollbacked if one element has a problem
sql errors not swallowed. The whole batch is still rollbacked …
=> Fix sql errors are swalled

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/java/com/powsybl/network/store/server/PreparedStatement.java, network-store-server/src/main/java/com/powsybl/network/store/server/QueryBuilder.java, network-store-server/src/main/java/com/powsybl/network/store/server/ResultSet.java, network-store-server/src/main/java/com/powsybl/network/store/server/Session.java
This allows for recovery when the connection drops (e.g. at database restart).
This also removes the need to use threadlocals because prepared statements are
not reused anymore, we recreate them each time (because the connection is returned
to the pool).
NO
Feature
Only one connection for …
=> Use connection pooling for NetworkStoreRepository.

network-store-server/src/main/resources/schema.sql
NO
Bug Fix
huge pkeys:
iidm   | switch                                                          | table | pgu_01o1005_o |                          | permanent   | 8799 MB | 
iidm   | switch_pkey                                                     | index | pgu_01o1005_o | switch                   | …
=> remove voltageLevelId from PK, it's useless

lombok.config, network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreService.java, network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java, network-store-client/src/main/java/com/powsybl/network/store/client/RestTemplateResponseErrorHandler.java, network-store-client/src/test/java/com/powsybl/network/store/client/RestNetworkStoreClientTest.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkStoreClient.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/OfflineNetworkStoreClient.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StoreClientUtils.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VariantManagerImpl.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-model/src/main/java/com/powsybl/network/store/model/ErrorObject.java, network-store-model/src/main/java/com/powsybl/network/store/model/TopLevelError.java, network-store-model/src/main/java/com/powsybl/network/store/model/utils/VariantUtils.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/java/com/powsybl/network/store/server/exceptions/JsonApiErrorResponseException.java, network-store-server/src/main/java/com/powsybl/network/store/server/exceptions/RestResponseEntityExceptionHandler.java
NO
Feature
cloneVariant on iidm network clones all objects so that the cloned variant is useable immediately and uses a lot of ram
Allow to clone a variant in networkstoreservice without paying for an iidm network clone when you are not going to …
=> add cloneNetwork

network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/NodeBreakerTerminalTest.java
Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>
=> The VL traverse to get a connectable bus must not exit (add a unit test)

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/NetworkGetBranchTest.java
No
Performance improvement
When writing a SLD diagram, we have extra query because when we search for a branch we begin by loading a line then a transfo. 
We first look at line and transfo cache before loading from server. We …
=> Improve Network.getBranch performance

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/java/com/powsybl/network/store/server/QueryCatalog.java
No
Performance improvement
getIdentifiablesWithSide is used to get lines, transfos 2 and 3 contained in a voltage level. So we have 2 ou 3 DB queries for each. It was because of Cassandra query limitations.
Why SQL, we can …
=> Remove getIdentifiablesWithSide

network-store-client/src/main/java/com/powsybl/network/store/client/NetworkStoreService.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
Signed-off-by: LE SAULNIER Kevin <kevin.lesaulnier@rte-france.com>
feature
A method importing a study was always passing null as parameters value
A new method allow the user to pass properties as parameters value
=> New method to import study with parameters

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractBranchImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/CreateNetworksUtil.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/LineTest.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java
Bug fix
we have NullPointerException error when adding connectablePositionExtension with a null value for feeder1 or null value for feeder2
(if any of the questions/checkboxes …
=> Fix null exception when creating connectable position extension

powsybl-network-store-client-parent/network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionImpl.java, powsybl-network-store-client-parent/network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java
NO
Bug fix
iidm export v1 uses busbarsection.getV, throws
iidm export v1 works
NO
Tests to be added in the tck
=> Add getV/getAngle impl for busbarsection, same as getTerminal().getI()

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractLoadingLimits.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractLoadingLimitsAdderImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/LineTest.java, network-store-model/src/main/java/com/powsybl/network/store/model/TemporaryLimitAttributes.java
This PR changes how temporary limits are sorted by acceptable durations when we retrieve them from database.
When we access the temporary limits stored in database, we've got a tree-map that naturally sorts acceptable durations
by ascending order, which is not conform to the interface specification …
=> return temporary limits by descending durations

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/PropertiesTest.java
no
This is bug fix about resource update and notification. When we remove a property from a given Identifiable object, the change is not persistent when we flush the network, and we got no notification (we should create onElementRemoved).
no
no
=> update resource and add notification when we remove a property

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/NetworkTest.java
Bug fix
getConnectedComponents and getSynchronousComponents method implementations in Network.BusView add the same component multiple times in the returned List.
A connected or synchronous component is now returned only once.
=> Fix duplication when getting network busview connected and synchronous components

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConnectablePositionImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/LoadTest.java
- [x ] The commit message follows our guidelines
Bug fix
When we try to get feeder1, feeder2, and feeder3 for a load, we get an NullPointerException 
When we try to get feeder1, feeder2, and feeder3 for a load, we get null
=> Fix get feeder position from extension

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImplTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/IdentifiableImplTest.java
No
Bug fix
`Identifiable.getProperty` when a default value is given is not working as expecting.
=> Fix Identifiable.getProperty with default value

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusbarSectionToInjectionAdapter.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/BusbarSectionGetPqTest.java
No
Bug fix
busbar section get p and get q throw an exception
busbar section get p and get q return a 0 as in core implementation
=> Fix busbar section get p and get q

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerViewImpl.java
No
Bug fix
When traversing a graph, the algorithm look at what is on the other side of switches. If there is a terminal and if it is not already in the set of traversed terminals, it is added to it and then it is "traversed" to see if the algorithm has to continue to traverse behind the terminal.
If there is no terminal on the other side of the switch or if the terminal is already in the set, the algorithm continue to traverse behind the node on the other side of the switch (be there a terminal or not).
The problem is that since #363, the edges of the graph are doubled (in order to have the …
=> Fix traverseFromTerminal when terminalNode2 already in traversedTerminals

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/ActivePowerControlExtensionTest.java
When using `identifiable.getExtension(Object.class)`, it matches all the extensions associated to the identifiable while we expect that it returns null. 
We need to change to strict type checking as it was done before implementing generalized extensions (see for example https://github.com/powsybl/powsybl-network-store/blob/0440f0d8aa40306b7cd559f889f2146ed70f1439/network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorImpl.java#L289)
`identifiable.getExtension(Object.class)` should return null and it should find an extension only if the exact extension class is given as parameter.
=> Strict type check in getExtension

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/InjectionObservabilityAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/extensions/InjectionObservabilityImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/extensions/InjectionObservabilityTest.java
Bug fix
An InjectionObservability extension cannot be added to a busbar section.
An InjectionObservability extension can now be added to a busbar section.
=> Fix casting pb with injection observability extension on BusbarSection.

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractBranchImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/OperationalLimitsTest.java
Bug fix
getOperationalLimitsGroups1() returns operational limits of side TWO.
getOperationalLimitsGroups1() returns operational limits of side ONE.
=> Fix getOperationalLimitsGroups1

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VscConverterStationAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VscConverterStationImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/VscTest.java, network-store-model/src/main/java/com/powsybl/network/store/model/VscConverterStationAttributes.java
2 TCK tests are KO (commented) because VscConverterStation.setRegulatingTerminal is not implemented. This PR adds persistent implementation for getRegulatingTerminal/setRegulatingTerminal in VscConverterStation.
=> add regulating terminal to converter station

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractTopology.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusBreakerTopology.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/BusBreakerCalculatedBusTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/BusBreakerTerminalTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/ComponentTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/BusTest.java
No
Update to make the test BusTest.testDisconnectConnect  work in powsybl network store. The changes are equivalent to what has been modified in this powsybl core PR : https://github.com/powsybl/powsybl-core/pull/2310
BusTest.testDisconnectConnect  is ignored (overriden and emptied)
Now the test passes (and the change introduced in powsybl core has been transfered to powsybl network store ie buses in bus breaker are valid even if they are not connected to a line or transfo (but to something else)
**Does this PR introduce a breaking …
=> update to fit TCK testDisconnectConnect

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractBranchImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/DanglingLineImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/LineTest.java
No.
Bug fix
It is not possible to add an OperationalLimitGroup to a branch, 3WT or danglingLine without selecting it. It is a problem when we import a case file that have OperationalLimitGroup on one branch's side but none is selected.
The OperationalLimitGroup is not selected when setCurrentLimits() is called. So we can use an AbstractLoadingLimitsAdder without activating the created OperationalLimitGroup. This bevahior fits to powsybl-core's one.
=> Do not select operationalLimitsGroup in setCurrentLimits

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CalculatedBus.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ConfiguredBusImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/LineTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/VoltageLevelTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/CurrentLimitsTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/MainConnectedComponentWithSwitchTest.java
Bug fix
Currently, when updating the V value in different topologies (NodeBreaker or BusBreaker), the synchronization between CalculatedBus and ConfiguredBus is not consistently handled across views, leading to potential inconsistencies in voltage values.
- When setV is called on getBus() from getBusBreakerView() in a NodeBreaker topology (which by default updates calculatedBusForBusBreakerView), calculatedBusForBusView should also be updated if it is not null.
- When setV is called on getBus() from getBusView() in a NodeBreaker …
=> Synchronize V Value Between CalculatedBus and ConfiguredBus

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BranchToInjectionAttributesAdapter.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ThreeWindingsTransformerToInjectionAttributesAdapter.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/ConnectionNotificationTest.java
Bug Fix
Tck tests fail in ConnectionNotificationTest
Tck tests now succeed in ConnectionNotificationTest
=> Fix notifications on terminal connection/disconnection

network-store-client/src/test/java/com/powsybl/network/store/client/CachedNetworkStoreClientTest.java, network-store-client/src/test/java/com/powsybl/network/store/client/PreloadingNetworkStoreClientTest.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CachedNetworkStoreClient.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CollectionCache.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/CollectionCacheTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/MockNetworkStoreClient.java
In CollectionCache, we sometimes overwrite the existing resource in the cache with the one retrieved from the server. This leads to bugs and inconsistencies especially with extensions. For example, if we load an equipment in the resources cache (Generator@1), then override this equipment in the cache (by loading it a second time by container => Generator@2).  
After that, when we load the extension attributes in the current cached equipment Generator@2, changes are not reflected in the initial reference (Generator@1).
I made a simple repeat here:
```java
@Test
public void testExtensionContainer() {
try (NetworkStoreService service = …
```
=> Ensure existing resources/extension attributes in the cache are not overwritten when loading from server

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractTapChanger.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/PhaseTapChangerImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RatioTapChangerImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/ThreeWindingsTransformerTest.java
no
it fixes abug when setting regulating on tap changers
removing a tapChanger from a collection set (set.remove(tapChanger)) does not work
it is fixed with adding equals and hashcode to tapChangers
=> fix regulating by setting phasetapchanger equals and hashcode

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/BusTopologyPointImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeTopologyPointImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalBusBreakerViewImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/TerminalNodeBreakerViewImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/MoveConnectableNotifTest.java
- [ x] The commit message follows our guidelines
When we move a connectable no notification sent
When we move a connectable a notification is sent
- [x ] No
=> Add notification when move connectable

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CollectionCache.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/CollectionCacheTest.java
No
It fixes an issue when trying to access extensions when they are not flushed/persisted yet. In the current behavior, a fetch on the server is done while it should not because everything is in memory.
In this network-store-server example test:
```java
try (NetworkStoreService service = createNetworkStoreService(randomServerPort)) {
Network network = EurostagTutorialExample1Factory.create(service.getNetworkFactory());
TwoWindingsTransformer twt = network.getTwoWindingsTransformer("NGEN_NHV1");
assertTrue(twt.getExtensions().isEmpty());
service.flush(network);
}
```
Even if the network is …
=> Fix initialization of collection cache for extensions

.github/workflows/maven.yml, .github/workflows/patch.yml, .github/workflows/release.yml
No
Adds automated workflows for release and patch processes
Release and patch processes are performed manually
release.yml: Handles major/minor version releases using the generic backend library workflow
patch.yml: Manages patch releases for existing versions
=> Implement release workflow

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractRegulatingEquipment.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/GeneratorImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RegulatingPoint.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/ShuntCompensatorImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/StaticVarCompensatorAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VscConverterStationAdderImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/VscConverterStationImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/GeneratorTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/GeneratorTest.java, network-store-model/src/main/java/com/powsybl/network/store/model/GeneratorAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/RegulatingPointAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/ShuntCompensatorAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/VscConverterStationAttributes.java, network-store-model/src/test/java/com/powsybl/network/store/model/TopLevelDocumentTest.java
linked with https://github.com/powsybl/powsybl-network-store-server/pull/85
=> move boolean regulating from equipment to RegulatingPoint

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NodeBreakerViewImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/VoltageLevelTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/NodeBreakerInternalConnectionsTest.java
Bug fix
Removing a voltage level with fork node fails with following error:
Technical error: java.lang.IllegalArgumentException: no such edge in graph: com.powsybl.network.store.iidm.impl.SwitchImpl@....
=> Fix removing voltage level with fork node

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/AttributesTest.java, network-store-model/src/main/java/com/powsybl/network/store/model/ExtensionAttributesIdResolver.java, network-store-model/src/main/java/com/powsybl/network/store/model/RawExtensionAttributes.java, network-store-model/src/main/java/com/powsybl/network/store/model/RawExtensionAttributesDeserializer.java
No
Extensions are lazily loaded from the server to identifiable when needed. On the first getIdentifiable(), extensions are not loaded in the identifiable. When we use getExtensionByName/getExtension(Extension.class) or getExtensions(), corresponding extensions are loaded in the identifiable if they exist on the server. 
We change the behavior of loading extensions when the loader of the extension to deserialize it is not present in the classpath (currently, it throws on getExtensions()).
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
In …
=> Fix deserialization error on getExtensions() when loader does not exist in classpath

network-store-model/src/test/java/com/powsybl/network/store/model/TopLevelDocumentTest.java
No
In this test, we do a serialization/deserialization test on a set with in not ordered by definition. I changed the test to have only one element in the set as we're not testing that here.
Failing test
Passing test
=> Fix flaky test on regulating equipments

network-store-client/src/main/java/com/powsybl/network/store/client/RestNetworkStoreClient.java, network-store-client/src/test/java/com/powsybl/network/store/client/RestNetworkStoreClientTest.java
No
When extensions without deserializer associated to them in the classpath are handled by the client, they're deserialized as RawExtensionAttributes. In the current implementation, these RawExtensionAttributes are loaded to the collection cache. 
This means that if one:
* load extension without deserializer in the classpath (they're cached)
* update the resource (the resource contains RawExtensionAttributes)
* flush the network
The client save the resource with RawExtensionAttributes but can't serialize it. 
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: ExtensionLoader not found (through reference …
```
=> Filter RawExtensionAttributes to avoid adding them to the cache

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/GeneratorTest.java
No
Bug fix
Code throws on the following (see UT):
1. remove a resource
2. clone network
3. set working variant to the new variant
That's because we use the same setResource() method for removing and switching variant (and other usages). When removing a resource we want to save the id of the removed resource and set the resource to null so we need a separate method. 
We also want to keep the id of the removed resource when switching variant.
1. No throw when switching variant after remove
2. id of the removed resource is available …
=> Fix id before removal when switching variant

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractTapChanger.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractTapChangerStepsReplacer.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/PhaseTapChangerImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/RatioTapChangerImpl.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/TwoWindingsTransformerTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/SwitchSetRetainedTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/TapChangerTest.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/tck/TwoWindingsTransformerTest.java
no
bug fix
when the low tap position is set position is not managed 
deplacing the position according to a new low tap position set
=> Fix tap position when setting low tap position

network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/AbstractIdentifiableImpl.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/NetworkObjectIndex.java, network-store-iidm-impl/src/test/java/com/powsybl/network/store/iidm/impl/GeneratorTest.java
No
Refacto after https://github.com/powsybl/powsybl-network-store/pull/524
idBeforeRemoval is handled in a separate method
idBeforeRemoval is handled in setResource.
=> Update setResource method to handle idBeforeRemoval

network-store-client/src/test/java/com/powsybl/network/store/client/CachedNetworkStoreClientTest.java, network-store-iidm-impl/src/main/java/com/powsybl/network/store/iidm/impl/CachedNetworkStoreClient.java
No
Bug fix
When you create a network and just after get something from this same network, instead of hitting the cache, you hit the server.
When you create a network and just after get this same network, you hit the cache as expected. The network collection is correctly initialized as every other collections.
=> Fix unexpected fetch on server after network is created
